IPoopToday/IPoopToday.Web/Controllers/ShitterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPoopToday.Web.Models.ShitterViewModels;
using Microsoft.AspNetCore.Mvc;
using IPoopToday.Web.Data;
using IPoopToday.Web.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using IPoopToday.Web.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using IPoopToday.Web.Services;

namespace IPoopToday.Web.Controllers
{
    [Authorize]
    public class ShitterController : Controller
    {
        private readonly ApplicationDbContext _db;

        private readonly UserManager<Shitee> _userManager;
        private IHealthService _healthService;

        public ShitterController(
            ApplicationDbContext db,
            UserManager<Shitee> userManager,
            IHealthService healthService)
        {
            _healthService = healthService;
            _userManager = userManager;
            _db = db;
        }

        private string UserID=>
            _userManager.GetUserId(User);

        [HttpGet]
        public ActionResult List()
        {
            var shitters = GetShittersForCurrentUser(true);
            var viewModels = shitters.Select(CreateViewModel).ToArray();
            return View(viewModels);
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(nameof(Map));
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(Guid id)
        {
            var shitter = GetShitterById(id);
            if (shitter == null) return NotFound();

            var shitterViewModel = CreateViewModel(shitter);

            return View(shitterViewModel);
        }

        #region Create

        [HttpGet]
        public ActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ShitterViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);
            ShitterTagsViewModel tags = Request.Form.GetShitterTags();

            var shitter = new Shitter() {
                Author = await _userManager.GetUserAsync(User),
                Location = new Geolocation(vm.Latitude, vm.Longitude),
                Name = vm.Name,
                Tags = (int)tags
            };

            _db.Shitters.Add(shitter);
            _db.SaveChanges();

            return RedirectToAction(nameof(Details), new {id = shitter.ID});
        }

        #endregion

        #region Edit

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            Shitter shitter = GetShitterByIdWithAccessCheck(id);
            if (shitter == null) return NotFound();
            var vm = CreateViewModel(shitter);

            return View("Create", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ShitterViewModel vm)
        {
            if (!ModelState.IsValid) return View("Create", vm);

            Shitter shitter = GetShitterByIdWithAccessCheck(vm.ID);
            if (shitter == null) return NotFound();

            shitter.Location = new Geolocation(vm.Latitude, vm.Longitude);
            shitter.Name = vm.Name;
            shitter.Tags = (int)Request.Form.GetShitterTags();

            _db.SaveChanges();

            return RedirectToAction(nameof(Details), new {id = vm.ID});
        }

        #endregion

        #region Map

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Map() => View();

        [HttpGet]
        [AllowAnonymous]
        public IActionResult GetAll()
        {
            return Json(GetAllShitters()
                .Select(CreateViewModel));
        }

        #endregion

        #region Delete

        [HttpGet]
        public ActionResult ConfirmDelete(Guid id)
        {
            var shitter = GetShitterByIdWithAccessCheck(id);
            if (shitter == null) return NotFound();
            return View(new ShitterViewModel(shitter.ID, shitter.Name,
                shitter.Location.Longitude, shitter.Location.Latitude));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([FromForm]Guid id)
        {
            try
            {
                var shitter = GetShitterByIdWithAccessCheck(id);
                _db.Shitters.Remove(shitter);
                _db.SaveChanges();
                return RedirectToAction(nameof(List));
            }
            catch
            {
                return RedirectToAction(nameof(ConfirmDelete), new {id = id});
            }
        }

        #endregion

        #region Vote

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Vote(ShitterVoteViewModel voteViewModel)
        {
            if (!ModelState.IsValid) return BadRequest();
            Shitter shitter = GetShitterById(voteViewModel.ShitterID);
            if (shitter == null) return NotFound();

            Shitee user = await _userManager.GetUserAsync(User);
            var vote = GetVoteForCurrentUser(voteViewModel.ShitterID);
            if (vote != null)
            {
                if (vote.IsPositive == voteViewModel.IsPositive)
                {
                    return await
                        InvokeHealthServiceAndReturn(
                            shitter.ID,
                            NoContent()
                        );
                }
                vote.IsPositive = voteViewModel.IsPositive;
            }
            else
            {
                vote = new Vote {
                    Shitter = shitter,
                    User = user,
                    Time = DateTime.Now,
                    IsPositive = voteViewModel.IsPositive
                };
                _db.Votes.Add(vote);
            }
            await _db.SaveChangesAsync();

            return await 
                InvokeHealthServiceAndReturn(
                    shitter.ID, Json(voteViewModel.IsPositive)
                );
        }

        #endregion

        private IList<Shitter> GetShittersForCurrentUser(bool loadReviews=false)
        {
            var query = GetAllShitters()
                .Where(x => x.Author.Id == UserID);

            if (loadReviews) query = query.Include(x => x.Reviews);

            return query.ToList();
        }

        private Shitter GetShitterByIdWithAccessCheck(Guid id)
        {
            var shitter = GetShitterById(id);
            if (!CheckShitterAccess(shitter)) return null;
            return shitter;
        }

        private Shitter GetShitterById(Guid id)
        {
            var rt= GetAllShitters()
                .Include(x=>x.Reviews)
                .SingleOrDefault(x => x.ID == id);

            return rt; 
        }

        private IQueryable<Shitter> GetAllShitters()
        {
            return _db.Shitters
                .Include(x => x.Location)
                .Include(x => x.Reviews)
                .Include(x => x.Author)
                .Include(x => x.Votes);
        }

        private bool CheckShitterAccess(Shitter shitter)
        {
            if (shitter?.Author?.Id != UserID) return false;
            return true;
        }

        private ShitterViewModel CreateViewModel(Shitter shitter)
        {
            var result = new ShitterViewModel {
                ID = shitter.ID,
                Latitude = shitter.Location.Latitude,
                Longitude = shitter.Location.Longitude,
                Name = shitter.Name,
                Tags = (ShitterTagsViewModel)shitter.Tags,
                VotesYes = shitter.VotesYes,
                VotesNo = shitter.VotesNo,
                IsPositiveVote = GetVoteForCurrentUser(shitter.ID)?.IsPositive,
                AuthorID = shitter.Author.Id
            };
            if (shitter.Reviews?.Count > 0)
            {
                result.AverageRating = shitter.Reviews.Average(x => x.Rating);
            }
            return result;
        }

        private async Task<IActionResult> InvokeHealthServiceAndReturn(Guid shitterID, IActionResult result)
        {
            HealthServiceResult serviceResult= await 
                _healthService.CheckAndDeleteAsync(shitterID);

            if(serviceResult.Deleted)
            {
                return RedirectToAction(nameof(Map));
            }

            return result;
        }

        private Vote GetVoteForCurrentUser(Guid shitterId)
        {
            var rt= _db.Votes
                .Where(x => x.ShitterID == shitterId)
                .SingleOrDefault(x => x.UserID == UserID);
            return rt;
        }
    }
}

IPoopToday/IPoopToday.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

@{ bool isSignedIn = true;}

@{ 
    //Oh, Lord, Please forgive me for my sins...
    @inject SignInManager<IPoopToday.Web.Entities.Shitee> SignInManager
    isSignedIn = SignInManager.IsSignedIn(User);
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@ViewData["Title"] - IPoopToday.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
    @RenderSection("Stylesheets", required: false)
    <link rel="stylesheet" href="~/css/stars.css"/>

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/lib/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/theme/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/css/theme/skins/_all-skins.min.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

</head>
<body class="hold-transition skin-blue sidebar-mini">

<div class="wrapper">
<!-- Main Header -->
<header class="main-header">
    <!-- Logo -->
    <a asp-action="Map" asp-controller="Shitter" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>LT</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>iPoop</b>today</span>
    </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        @if (isSignedIn)
        {
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
        }
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
            
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    @{Html.RenderPartial("_LoginPartial");}
                
                </li>
            </ul>
        </div>
    </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
@if (isSignedIn)
{
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- /.search form -->
            <!-- Sidebar Menu -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">iPoop.today</li>
                <!-- Optionally, you can add icons to the links -->
                <li class="@(ViewBag?.CreatingShitter == true ? "active" : string.Empty)"><a asp-action="Create" asp-controller="Restroom"><i class="fa fa-database"></i> <span>Register a Restroom!</span></a></li>
                <li class="@(ViewBag?.MappingShitters == true ? " active" : string.Empty)"><a asp-action="Map" asp-controller="Restroom"><i class="fa fa-map"></i> <span>Map of Restrooms</span></a></li>
                <li class="@(ViewBag?.ListingShitters == true ? "active" : string.Empty)"><a asp-action="List" asp-controller="Restroom"><i class="fa fa-user"></i> <span>My Restrooms</span></a></li>
                @*<li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-link"></i> <span>Multilevel</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="#">Link in level 2</a></li>
                        <li><a href="#">Link in level 2</a></li>
                    </ul>
                </li>*@
            </ul>
            <!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper" style="@(isSignedIn==false?"margin-left: 0px !important":string.Empty)">
    @RenderBody()
</div>
<!-- /.content-wrapper -->
<!-- Main Footer -->
@*<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
</footer>*@
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="pull-right-container">
                                <span class="label label-danger pull-right">70%</span>
                            </span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>
    
<script src="~/js/stars.js"></script>
<!-- jQuery 3 -->
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="~/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- AdminLTE App -->
<script src="~/js/theme/adminlte.min.js"></script>

@RenderSection("Scripts", required: false)
</body>
</html>