IPoopToday/IPoopToday.Web/Entities/Shitter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace IPoopToday.Web.Entities
{
    public class Shitter:EntityBase<Guid>
    {
        [Required]
        public Shitee Author { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public Geolocation Location { get; set; }
        public int Tags { get; set; }
        public virtual List<Vote> Votes { get; set; }
        public  virtual  List<Review> Reviews { get; set; }

        [NotMapped]
        public int VotesYes => Votes?.Count(x => x.IsPositive) ?? 0;
        [NotMapped]
        public int VotesNo => Votes?.Count(x => !x.IsPositive) ?? 0;
    }
}

IPoopToday/IPoopToday.Web/Models/ShitterViewModels/ShitterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace IPoopToday.Web.Models.ShitterViewModels
{
    public class ShitterViewModel
    {
        public ShitterViewModel()
        {
        }

        public ShitterViewModel(Guid id, string name,
            double latitude, double longitude)
        {
            ID = id;
            Name = name;
            Latitude = latitude;
            Longitude = longitude;
        }

        [Required]
        public Guid ID { get; set; }

        [RegularExpression("^([0-9]+(\\.[0-9]+)?)$", ErrorMessage = "Incorrent format")]
        public double Latitude { get; set; }

        [RegularExpression("^([0-9]+(\\.[0-9]+)?)$", ErrorMessage = "Incorrent format")]
        public double Longitude { get; set; }

        [Required]
        [StringLength(255, MinimumLength = 1)]
        public string Name { get; set; }

        [RegularExpression("^([0-9]+(\\.[0-9]+)?)?$", ErrorMessage = "Incorrent format")]
        public decimal Price { get; set; }

        [Required]
        public ShitterTagsViewModel Tags { get; set; }
        public string DebugMessage { get; set; }
        
        public int VotesNo { get; set; }
        public int VotesYes { get; set; }

        public double Opacity
        {
            get
            {
                double ratio = (double)VotesYes / VotesNo;
                if (double.IsNaN(ratio))
                    return 0.5;
                if (double.IsInfinity(ratio))
                    return 1;
                return Math.Max(1, ratio);
            }
        }
        public bool? IsPositiveVote { get; set; }
        public bool IsPaid => Tags.HasFlag(ShitterTagsViewModel.Paid);
        public string AuthorID { get; set; }
        public double AverageRating { get; set; }
        public bool IsNew => ID == Guid.Empty;
        public int ReviewsCount { get; set; }
    }
}

IPoopToday/IPoopToday.Web/Controllers/ReviewController.cs
using System.Linq;
using System.Threading.Tasks;
using IPoopToday.Web.Data;
using IPoopToday.Web.Entities;
using IPoopToday.Web.Models.ReviewViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IPoopToday.Web.Controllers
{
    [Authorize]
    public class ReviewController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Shitee> _userManager;
        public ReviewController(ApplicationDbContext context, UserManager<Shitee> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(ReviewViewModel model)
        {
            if (!ModelState.IsValid) return BadRequest();

            var shitter = _context.Shitters
                                  .Include(x => x.Reviews)
                                  .FirstOrDefault(x => x.ID == model.ShitterID);
            if (shitter == null)
            {
                return NotFound();
            }

            shitter.Reviews.Add(new Review
            {
                Author = await _userManager.GetUserAsync(User),
                Content = model.Content,
                Rating = (byte)model.Rating
            });

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(ShitterController.Details), "Shitter", new {id = model.ShitterID});
        }

    }
}

IPoopToday/IPoopToday.Web/Controllers/ShitterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPoopToday.Web.Models.ShitterViewModels;
using Microsoft.AspNetCore.Mvc;
using IPoopToday.Web.Data;
using IPoopToday.Web.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using IPoopToday.Web.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using IPoopToday.Web.Services;

namespace IPoopToday.Web.Controllers
{
    [Authorize]
    public class ShitterController : Controller
    {
        private readonly ApplicationDbContext _db;

        private readonly UserManager<Shitee> _userManager;
        private IHealthService _healthService;

        public ShitterController(
            ApplicationDbContext db,
            UserManager<Shitee> userManager,
            IHealthService healthService)
        {
            _healthService = healthService;
            _userManager = userManager;
            _db = db;
        }

        private string UserID=>
            _userManager.GetUserId(User);

        [HttpGet]
        public ActionResult List()
        {
            var shitters = GetShittersForCurrentUser(true);
            var viewModels = shitters.Select(CreateViewModel).ToArray();
            return View(viewModels);
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(nameof(Map));
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(Guid id)
        {
            var shitter = GetShitterById(id);
            if (shitter == null) return NotFound();

            var shitterViewModel = CreateViewModel(shitter);

            return View(shitterViewModel);
        }

        #region Create

        [HttpGet]
        public ActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ShitterViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);
            ShitterTagsViewModel tags = Request.Form.GetShitterTags();

            var shitter = new Shitter() {
                Author = await _userManager.GetUserAsync(User),
                Location = new Geolocation(vm.Latitude, vm.Longitude),
                Name = vm.Name,
                Tags = (int)tags
            };

            _db.Shitters.Add(shitter);
            _db.SaveChanges();

            return RedirectToAction(nameof(Details), new {id = shitter.ID});
        }

        #endregion

        #region Edit

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            Shitter shitter = GetShitterByIdWithAccessCheck(id);
            if (shitter == null) return NotFound();
            var vm = CreateViewModel(shitter);

            return View("Create", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ShitterViewModel vm)
        {
            if (!ModelState.IsValid) return View("Create", vm);

            Shitter shitter = GetShitterByIdWithAccessCheck(vm.ID);
            if (shitter == null) return NotFound();

            shitter.Location = new Geolocation(vm.Latitude, vm.Longitude);
            shitter.Name = vm.Name;
            shitter.Tags = (int)Request.Form.GetShitterTags();

            _db.SaveChanges();

            return RedirectToAction(nameof(Details), new {id = vm.ID});
        }

        #endregion

        #region Map

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Map() => View();

        [HttpGet]
        [AllowAnonymous]
        public IActionResult GetAll()
        {
            return Json(GetAllShitters()
                .Select(CreateViewModel));
        }

        #endregion

        #region Delete

        [HttpGet]
        public ActionResult ConfirmDelete(Guid id)
        {
            var shitter = GetShitterByIdWithAccessCheck(id);
            if (shitter == null) return NotFound();
            return View(new ShitterViewModel(shitter.ID, shitter.Name,
                shitter.Location.Longitude, shitter.Location.Latitude));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([FromForm]Guid id)
        {
            try
            {
                var shitter = GetShitterByIdWithAccessCheck(id);
                _db.Shitters.Remove(shitter);
                _db.SaveChanges();
                return RedirectToAction(nameof(List));
            }
            catch
            {
                return RedirectToAction(nameof(ConfirmDelete), new {id = id});
            }
        }

        #endregion

        #region Vote

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Vote(ShitterVoteViewModel voteViewModel)
        {
            if (!ModelState.IsValid) return BadRequest();
            Shitter shitter = GetShitterById(voteViewModel.ShitterID);
            if (shitter == null) return NotFound();

            Shitee user = await _userManager.GetUserAsync(User);
            var vote = GetVoteForCurrentUser(voteViewModel.ShitterID);
            if (vote != null)
            {
                if (vote.IsPositive == voteViewModel.IsPositive)
                {
                    return await
                        InvokeHealthServiceAndReturn(
                            shitter.ID,
                            NoContent()
                        );
                }
                vote.IsPositive = voteViewModel.IsPositive;
            }
            else
            {
                vote = new Vote {
                    Shitter = shitter,
                    User = user,
                    Time = DateTime.Now,
                    IsPositive = voteViewModel.IsPositive
                };
                _db.Votes.Add(vote);
            }
            await _db.SaveChangesAsync();

            return await 
                InvokeHealthServiceAndReturn(
                    shitter.ID, Json(voteViewModel.IsPositive)
                );
        }

        #endregion

        private IList<Shitter> GetShittersForCurrentUser(bool loadReviews=false)
        {
            var query = GetAllShitters()
                .Where(x => x.Author.Id == UserID);

            if (loadReviews) query = query.Include(x => x.Reviews);

            return query.ToList();
        }

        private Shitter GetShitterByIdWithAccessCheck(Guid id)
        {
            var shitter = GetShitterById(id);
            if (!CheckShitterAccess(shitter)) return null;
            return shitter;
        }

        private Shitter GetShitterById(Guid id)
        {
            var rt= GetAllShitters()
                .Include(x=>x.Reviews)
                .SingleOrDefault(x => x.ID == id);

            return rt; 
        }

        private IQueryable<Shitter> GetAllShitters()
        {
            return _db.Shitters
                .Include(x => x.Location)
                .Include(x => x.Reviews)
                .Include(x => x.Author)
                .Include(x => x.Votes);
        }

        private bool CheckShitterAccess(Shitter shitter)
        {
            if (shitter?.Author?.Id != UserID) return false;
            return true;
        }

        private ShitterViewModel CreateViewModel(Shitter shitter)
        {
            var result = new ShitterViewModel {
                ID = shitter.ID,
                Latitude = shitter.Location.Latitude,
                Longitude = shitter.Location.Longitude,
                Name = shitter.Name,
                Tags = (ShitterTagsViewModel)shitter.Tags,
                VotesYes = shitter.VotesYes,
                VotesNo = shitter.VotesNo,
                IsPositiveVote = GetVoteForCurrentUser(shitter.ID)?.IsPositive,
                AuthorID = shitter.Author.Id
            };
            if (shitter.Reviews?.Count > 0)
            {
                result.AverageRating = shitter.Reviews.Average(x => x.Rating);
            }
            return result;
        }

        private async Task<IActionResult> InvokeHealthServiceAndReturn(Guid shitterID, IActionResult result)
        {
            HealthServiceResult serviceResult= await 
                _healthService.CheckAndDeleteAsync(shitterID);

            if(serviceResult.Deleted)
            {
                return RedirectToAction(nameof(Map));
            }

            return result;
        }

        private Vote GetVoteForCurrentUser(Guid shitterId)
        {
            var rt= _db.Votes
                .Where(x => x.ShitterID == shitterId)
                .SingleOrDefault(x => x.UserID == UserID);
            return rt;
        }
    }
}

IPoopToday/IPoopToday.Web/ViewComponents/ReviewListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPoopToday.Web.Data;
using IPoopToday.Web.Models.ReviewViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IPoopToday.Web.ViewComponents
{
    public class ReviewListViewComponent : ViewComponent
    { 
        private ApplicationDbContext _db;
        public ReviewListViewComponent(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(Guid shitterId)
        {
            await Task.Yield();
            var items = GetReviews(shitterId);
            return View(items);
        }


        public IEnumerable<ReviewViewModel> GetReviews(Guid shitterId)
        {
            var reviews = _db.Shitters
                            .Include(x => x.Reviews)
                            .FirstOrDefault(x => x.ID == shitterId)?
                            .Reviews
                            .Select(x => new ReviewViewModel
                                    {
                                        ShitterID = shitterId,
                                        Content = x.Content,
                                        Rating = x.Rating
                                    }
                                    );
            return reviews;
        }
    }
}

IPoopToday/IPoopToday.Web/Views/Shitter/ConfirmDelete.cshtml
@model ShitterViewModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShitterViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID"/>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="List">Back to List</a>
        </div>
    </form>
</div>

IPoopToday/IPoopToday.Web/Views/Shitter/Create.cshtml
@using System
@using IPoopToday.Web.Entities
@using Microsoft.EntityFrameworkCore.Query.Internal
@model ShitterViewModel
@inject UserManager<Shitee> ShiteeManager

@{
    string action = (Model?.IsNew ?? true) ? "Create" : "Edit";
    ViewData["Title"] = action;
}
<div class="custom-table" style="padding-top: 20px">
    <section class="col-sm-4 col-sm-offset-3">
        <h2 style="margin-top: 0px;">@(action) restroom</h2>
        <br/>
        @action
        <form asp-action="@(action)">
            <div class="form-horizontal">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Latitude" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Latitude" class="form-control"/>
                        <span asp-validation-for="Latitude" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Longitude" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Longitude" class="form-control"/>
                        <span asp-validation-for="Longitude" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-5 col-md-10">
                        <input id="btn-set-pos" type="button"
                               onClick="setCurrentPosition()" class="btn btn-default" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        @foreach (var val in Enum
                            .GetValues(typeof(ShitterTagsViewModel))
                            .Cast<ShitterTagsViewModel>()
                            .Where(x => x != ShitterTagsViewModel.None))
                        {
                            string chkId = Guid.NewGuid().ToString();

                            <div>
                                <label for="@chkId">#@val.ToString()</label>
                                <input name="tag_@val.ToString()" id="@chkId"
                                       type="checkbox" @((Model?.Tags.HasFlag(val)??false)?"checked":"")/>
                            </div>
                        }
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-5 col-md-10">
                        <input type="submit" value="@(action)" class="btn btn-default"/>
                    </div>
                </div>
            </div>
        </form>
    </section>
</div>

@section Scripts
{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script>
        $(document).ready(() => {
            setButtonEnabled(true);
            if ("@action" === "Create") setCurrentPosition();
        });

        function setCurrentPosition() {
            setButtonEnabled(false);
            getPos(function (coords) {
                $('#Latitude').val(coords.lat);
                $('#Longitude').val(coords.lng);
                setButtonEnabled(true);
            });
        }

        function getPos(callback) {
            navigator.geolocation.watchPosition(function (myLatlng) {
                    var mapOptions = { lat: myLatlng.coords.latitude, lng: myLatlng.coords.longitude };
                    callback(mapOptions);
                },
                function(error) {
                    var mapOptions = { lat: 43.446405, lng: 24.616477 };
                    callback(mapOptions);
                }, { timeout: 1000 });
        }

        function setButtonEnabled(state) {
            var btn = $('#btn-set-pos');
            if (state) {
                btn.val("Get location...");
                btn.prop("disabled", false);
            } else {
                $('#btn-set-pos').val("Waiting for location...");
                $('#btn-set-pos').prop("disabled", true);
            }
        }
    </script>
}

IPoopToday/IPoopToday.Web/Views/Shitter/Details.cshtml
@using System
@using IPoopToday.Web.Models.ReviewViewModels
@using IPoopToday.Web.Controllers
@using IPoopToday.Web.Entities
@inject UserManager<Shitee> UserManager;
@model ShitterViewModel

@{

    ViewData["Title"] = "View";
}

@section Stylesheets{
    <style>
        .view-wrapper {
            padding-top: 30px;
            padding-left: 10%;
        }

        h1 { display: inline; }

        .avg-rating {
            display: inline;
            padding-bottom: 15px;
        }

        .avg-rating-wrapper { padding-left: 50px; }

        .GPS-Label { font-weight: normal; }

        .long-label { margin-left: 20px; }
        .shitter-tag {
            
            font-size: 16px;
        }
    </style>
}

<div class="view-wrapper row">
    <div class="row">
        <h1>
            <label>@Model.Name</label>
        </h1>


        <span class="avg-rating-wrapper">
            @for (int i = 1; i <= Model.AverageRating; i++)
            {
                <img src="~/images/stars/star-on.svg" class="avg-rating"/>
            }
            @for (int i = (int) Model.AverageRating + 1; i <= 5; i++)
            {
                <img src="~/images/stars/star-off.svg" class="avg-rating"/>
            }
        </span>
        
        <div class="col-sm-offset-7" style="display: inline">
            <div class="btn-group ">
                <button onclick="vote(true)" id="btn-vote-yes" class="btn btn-success">
                    Submit Vote Y<br/>
                    <span id="yes-votes" style="text-align: center"></span>
                </button>
                <button onclick="vote(false)" id="btn-vote-no" class="btn btn-danger">
                    Submit Vote N<br/>
                    <span id="no-votes" style="text-align: center"></span>
                </button>

            </div>
        </div>
    </div>
    <div class="row" style="display: inline;">
        <label class="GPS-Label">&nbsp;&nbsp;&nbsp;&nbsp;Latitude: @Model.Latitude</label>
        <label class="GPS-Label long-label">Longitude: @Model.Longitude</label>
    </div>


    <br/>

    <div class="form-group">
        <div class=" col-md-10">
            @foreach (ShitterTagsViewModel value in Enum.GetValues(typeof(ShitterTagsViewModel)))
            {
                if (value != ShitterTagsViewModel.None &&
                    Model.Tags.HasFlag(value))
                {
                    <div style="display: inline">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#<span class="shitter-tag"><i>@(value.ToString())</i></span>
                    </div>
                }
            }
        </div>
    </div>
    <br/>

    @if (Model.AuthorID == UserManager.GetUserId(User))
    {
        <div class="row">
            <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-success">Edit</a>
        </div>
    }
    <div class="row">
        @{ await Html.RenderPartialAsync("_CreateReview", new ReviewViewModel {ShitterID = Model.ID, Rating = Model.AverageRating}); }
    </div>
    <div class="row">
        @await Component.InvokeAsync("ReviewList", new {shitterId = Model.ID})
    </div>


</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <script>
        var positiveVote = @Json.Serialize(Model.IsPositiveVote);
        var yesVotes = @Model.VotesYes;
        var noVotes = @Model.VotesNo;
        var shitterId = "@Model.ID";
        var voteUrl = "@Url.Action(nameof(ShitterController.Vote))";
    </script>

    <script src="~/js/vote.js" asp-append-version="true"></script>
}

IPoopToday/IPoopToday.Web/Views/Shitter/List.cshtml
@using System.Collections.Generic
@model IEnumerable<ShitterViewModel>

@{
    ViewData["Title"] = "Index";
    ViewBag.ListingShitters = true;
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th>
                @Html.DisplayNameFor(x=>x.AverageRating)
            </th>
                <th>
                    @Html.DisplayNameFor(model => model.Longitude)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Latitude)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <span class="center-block">
                    @for(int i = 1; i <=item.AverageRating; i++)
                    {
                        <img src="~/images/stars/star-on.svg"/>
                    }
                    @for (int i = (int)item.AverageRating+1; i <= 5; i++)
                    {
                        <img src="~/images/stars/star-off.svg" />
                    }
                </span>
                @*@Html.DisplayFor(x=>item.AverageRating)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Latitude)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a>
                <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                <a asp-action="ConfirmDelete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

IPoopToday/IPoopToday.Web/Views/Shitter/Map.cshtml
@using IPoopToday.Web.Controllers
@using Microsoft.AspNetCore.Mvc
@{
    ViewData["Title"] = "Map";
    ViewBag.MappingShitters = true;
}

@section Stylesheets
{
    <style>

        #map {
            height: calc(100vh - 50px);
            margin-top: 0px;
        }
        .content,
        .container-fluid { padding: 0px !important; }

        .gm-svpc {
            display: none; /*Hide google street view control*/
        }
    </style>
}

<div id="map" class="map-img z-depth-5"></div>
<script type="text/javascript">
    let mapCentered=false;
    function initMap() {
        getPos(function(mapOptions) {
        if(mapCentered)return;
        mapCentered=true;
            var map = new google.maps.Map(document.getElementById("map"), mapOptions);

            var shitters;
            var jqxhr = $.getJSON("@Url.Action(nameof(ShitterController.GetAll))",
                    function() {
                        shitters = JSON.parse(jqxhr.responseText);
                        for (var i = 0; i < shitters.length; i++) {
                            marker = createMarker(shitters[i], map);
                            google.maps.event.addListener(marker, 'click',
                                function() {
                                    window.location.href = this.url;
                                });
                        }
                    })
                .done(function() {
                })
                .fail(function() {
                });
        });
    }

    function createMarker(shitter, map) {
        return new google.maps.Marker({
            position: {
                lat: shitter.latitude,
                lng: shitter.longitude
            },
            title: shitter.name,
            icon: {
                url: getShitterIcon(shitter),
                scaledSize: new google.maps.Size(40, 40)
            },
            map: map,
            url: getDetailsUrl(shitter),
            opacity: shitter.opacity
        });
    }

    function getShitterIcon(shitter) {
        var iconsFolder = "/images/map-icons/";
        var iconName = "toilet";
        var iconExtension = ".png";
        var iconSuffix = "free";
        if (shitter.isPaid) {
            iconSuffix = "paid";
        }
        return iconsFolder + iconName + "-" + iconSuffix + iconExtension;
    }

    function getDetailsUrl(shitter) {
        return '@Url.Action(nameof(ShitterController.Details))/' + shitter.id;
    }

    function getPos(callback) {
        navigator.geolocation.watchPosition(function(myLatlng) {
                var mapOptions = {
                    zoom: 18,
                    center: { lat: myLatlng.coords.latitude, lng: myLatlng.coords.longitude }
                }
                callback(mapOptions);
            },
            function(error) {
                var mapOptions = {
                    zoom: 7,
                    center: { lat: 42.511765, lng: 24.972117 }
                }
                callback(mapOptions);
            });
    }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBIjWx_A8oq0_u6BJb96ydhlT_2iM1VG4&libraries=visualization&callback=initMap" async defer></script>

IPoopToday/IPoopToday.Web/Views/Shitter/_CreateReview.cshtml
@using IPoopToday.Web.Models.ReviewViewModels
@using Microsoft.AspNetCore.Mvc.Rendering
@model ReviewViewModel
<div class="form-group" id="add-review">
    <form asp-action="Add" asp-controller="Review" method="post">
        <div class="form-horizontal col-sm-5 col-sm-offset-1">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="ShitterID" />
            <div class="form-group">
                <label asp-for="Rating" class="col-md-12 control-label" style="text-align: left"></label>
                <div class="col-md-12">
                    @{ Html.RenderPartial("~/Views/Shared/Partial/StarsPartial.cshtml");}
                    <input type="hidden" asp-for="Rating" id="input-rating" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="col-md-12 control-label"style="text-align: left">Comment (optional):</label>
                <div class="col-md-12">
                    <textarea asp-for="Content" class="form-control" ></textarea>
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
            </div>
            

            <div class="form-group">
                <div class="col-md-offset-0 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </form>
</div>